"""Interactive onboarding wizard for Roost.

Runs BEFORE docker compose — generates .env from user answers.
Designed to be used in a classroom setting where the instructor
explains each step as the student fills it in.
"""

import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

# ANSI colours
BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RED = "\033[91m"
RESET = "\033[0m"

BANNER = f"""
{CYAN}{BOLD}╔══════════════════════════════════════════════╗
║          🏠  Welcome to Roost Setup          ║
║     Your AI Agent, Your Infrastructure       ║
╚══════════════════════════════════════════════╝{RESET}

This wizard will walk you through setting up your
personal AI agent. Each step builds on the last.

{DIM}Your instructor will explain what each value means
and where to find it.{RESET}
"""

AI_PROVIDERS = {
    "1": {
        "name": "Gemini",
        "key_var": "GEMINI_API_KEY",
        "provider": "gemini",
        "prompt": "Paste your Gemini API key",
        "hint": "Get one free at https://aistudio.google.com/apikey",
    },
    "2": {
        "name": "Claude",
        "key_var": "CLAUDE_API_KEY",
        "provider": "claude",
        "prompt": "Paste your Claude API key",
        "hint": "Get one at https://console.anthropic.com/settings/keys",
    },
    "3": {
        "name": "OpenAI",
        "key_var": "OPENAI_API_KEY",
        "provider": "openai",
        "prompt": "Paste your OpenAI API key",
        "hint": "Get one at https://platform.openai.com/api-keys",
    },
    "4": {
        "name": "Ollama (local, free)",
        "key_var": None,
        "provider": "ollama",
        "prompt": None,
        "hint": "Runs locally — no API key needed",
    },
}


def _ask(prompt: str, default: str = "", required: bool = False,
         secret: bool = False) -> str:
    """Prompt the user for input with optional default."""
    suffix = f" [{default}]" if default else ""
    marker = f"{GREEN}→{RESET}"

    while True:
        try:
            if secret:
                import getpass
                value = getpass.getpass(f"{marker} {prompt}{suffix}: ")
            else:
                value = input(f"{marker} {prompt}{suffix}: ")
        except (EOFError, KeyboardInterrupt):
            print(f"\n{RED}Setup cancelled.{RESET}")
            sys.exit(1)

        value = value.strip()
        if not value and default:
            return default
        if not value and required:
            print(f"  {RED}This field is required.{RESET}")
            continue
        return value


def _ask_choice(prompt: str, choices: dict[str, str]) -> str:
    """Present numbered choices and return the key."""
    print(f"\n{BOLD}{prompt}{RESET}")
    for key, label in choices.items():
        print(f"  {CYAN}{key}{RESET}) {label}")

    while True:
        choice = _ask("Your choice", required=True)
        if choice in choices:
            return choice
        print(f"  {RED}Please enter one of: {', '.join(choices.keys())}{RESET}")


def _ask_yn(prompt: str, default: bool = True) -> bool:
    """Yes/no question."""
    hint = "Y/n" if default else "y/N"
    answer = _ask(f"{prompt} [{hint}]")
    if not answer:
        return default
    return answer.lower().startswith("y")


def _section(title: str) -> None:
    """Print a section header."""
    print(f"\n{BOLD}{'─' * 50}")
    print(f"  {title}")
    print(f"{'─' * 50}{RESET}")


def _validate_telegram_token(token: str) -> bool:
    """Quick format check for Telegram bot tokens."""
    parts = token.split(":")
    return len(parts) == 2 and parts[0].isdigit() and len(parts[1]) > 20


def _test_telegram_token(token: str) -> tuple[bool, str]:
    """Call Telegram getMe to validate the token."""
    try:
        import urllib.request
        import json
        url = f"https://api.telegram.org/bot{token}/getMe"
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            if data.get("ok"):
                bot_name = data["result"].get("username", "unknown")
                return True, bot_name
            return False, "API returned error"
    except Exception as e:
        return False, str(e)


def _generate_env(answers: dict) -> str:
    """Generate .env file content from wizard answers."""
    lines = [
        "# =============================================================================",
        "# Roost Configuration — generated by 'roost onboard'",
        "# =============================================================================",
        "",
        "# -- Core --",
        f"SESSION_SECRET={answers['session_secret']}",
        f"WEB_USERNAME={answers['web_username']}",
        f"WEB_PASSWORD={answers['web_password']}",
        "HOST=0.0.0.0",
        "PORT=8080",
        "",
        "# -- Feature Flags --",
        "GOOGLE_ENABLED=false",
        "GMAIL_ENABLED=false",
        "MS_ENABLED=false",
        f"AI_ENABLED={'true' if answers.get('ai_provider') else 'false'}",
        f"TELEGRAM_ENABLED={'true' if answers.get('telegram_token') else 'false'}",
        "NOTION_ENABLED=false",
        "INFRA_ENABLED=true",
        "SSH_ENABLED=true",
        "",
        "# -- AI Provider --",
        f"AGENT_PROVIDER={answers.get('ai_provider', 'gemini')}",
    ]

    # AI-specific keys
    provider = answers.get("ai_provider", "")
    if provider == "gemini":
        lines.append(f"GEMINI_API_KEY={answers.get('ai_key', '')}")
    elif provider == "claude":
        lines.append(f"CLAUDE_API_KEY={answers.get('ai_key', '')}")
    elif provider == "openai":
        lines.append(f"OPENAI_API_KEY={answers.get('ai_key', '')}")
    elif provider == "ollama":
        lines.append(f"OLLAMA_URL={answers.get('ollama_url', 'http://localhost:11434/v1')}")

    lines += [
        "",
        "# -- Telegram Bot --",
        f"TELEGRAM_BOT_TOKEN={answers.get('telegram_token', '')}",
        f"TELEGRAM_ALLOWED_USERS={answers.get('telegram_user_id', '')}",
        "",
        "# -- Google OAuth (configure later via web settings) --",
        "GOOGLE_CLIENT_ID=",
        "GOOGLE_CLIENT_SECRET=",
        "",
        "# -- Microsoft Graph (configure later via web settings) --",
        "MS_CLIENT_ID=",
        "MS_CLIENT_SECRET=",
        "MS_TENANT_ID=",
        "",
        "# -- Notion (configure later via web settings) --",
        "NOTION_API_TOKEN=",
        "",
        "# -- SSH Access --",
        f"SSH_PASSWORD={answers.get('ssh_password', answers['web_password'])}",
        "",
        "# -- Anthropic (for Claude Code inside container) --",
        "ANTHROPIC_API_KEY=",
        "",
    ]
    return "\n".join(lines)


def _build_docker_compose_args(answers: dict) -> list[str]:
    """Build docker compose command with correct build args."""
    has_ai = bool(answers.get("ai_provider"))
    has_telegram = bool(answers.get("telegram_token"))

    cmd = ["docker", "compose", "build"]

    # Map feature flags to build args
    build_args = {
        "ENABLE_AI": "true" if has_ai else "false",
        "ENABLE_TELEGRAM": "true" if has_telegram else "false",
        "ENABLE_GOOGLE": "false",
        "ENABLE_MICROSOFT": "false",
        "ENABLE_NOTION": "false",
        "ENABLE_INFRA": "false",
    }
    for key, val in build_args.items():
        cmd.extend(["--build-arg", f"{key}={val}"])

    return cmd


def run_onboard() -> None:
    """Run the interactive onboarding wizard."""
    print(BANNER)

    # Detect project root (where docker-compose.yml lives)
    project_root = Path.cwd()
    compose_file = project_root / "docker-compose.yml"
    if not compose_file.exists():
        # Try parent directory
        project_root = Path(__file__).resolve().parent.parent.parent
        compose_file = project_root / "docker-compose.yml"

    if not compose_file.exists():
        print(f"{RED}Error: Can't find docker-compose.yml.{RESET}")
        print(f"Run this from the Roost project directory.")
        sys.exit(1)

    env_file = project_root / ".env"
    answers: dict = {}

    # ── Step 1: AI Provider ──────────────────────────────────────

    _section("Step 1: Choose Your AI Engine")
    print(f"""
{DIM}Your AI agent needs a brain. Pick which AI service
to use. You can change this later.{RESET}
""")

    provider_choices = {k: v["name"] for k, v in AI_PROVIDERS.items()}
    choice = _ask_choice("Which AI provider?", provider_choices)
    provider = AI_PROVIDERS[choice]
    answers["ai_provider"] = provider["provider"]

    if provider["key_var"]:
        print(f"\n  {DIM}{provider['hint']}{RESET}")
        api_key = _ask(provider["prompt"], required=True)
        answers["ai_key"] = api_key
        print(f"  {GREEN}✓{RESET} {provider['name']} configured")
    else:
        # Ollama — ask for URL
        print(f"\n  {DIM}{provider['hint']}{RESET}")
        ollama_url = _ask("Ollama API URL", default="http://localhost:11434/v1")
        answers["ollama_url"] = ollama_url
        print(f"  {GREEN}✓{RESET} Ollama configured at {ollama_url}")

    # ── Step 2: Telegram Bot ─────────────────────────────────────

    _section("Step 2: Connect Telegram")
    print(f"""
{DIM}Your agent lives in Telegram. You'll need:
1. A bot token from @BotFather
2. Your Telegram user ID{RESET}
""")

    if _ask_yn("Set up Telegram now?"):
        while True:
            token = _ask("Bot token from @BotFather", required=True)
            if not _validate_telegram_token(token):
                print(f"  {RED}That doesn't look like a valid bot token.{RESET}")
                print(f"  {DIM}Format: 123456789:ABCdef... (number:letters){RESET}")
                if not _ask_yn("Try again?"):
                    break
                continue

            # Test the token
            print(f"  {DIM}Testing connection...{RESET}", end=" ", flush=True)
            ok, result = _test_telegram_token(token)
            if ok:
                print(f"{GREEN}✓{RESET} Connected to @{result}")
                answers["telegram_token"] = token
            else:
                print(f"{RED}✗{RESET} Failed: {result}")
                if not _ask_yn("Try a different token?"):
                    break
                continue
            break

        if answers.get("telegram_token"):
            print(f"""
  {DIM}Your Telegram user ID is a number that identifies you.
  Send /start to @userinfobot on Telegram to find it.{RESET}
""")
            user_id = _ask("Your Telegram user ID", required=True)
            while not user_id.isdigit():
                print(f"  {RED}User ID should be a number (e.g. 123456789){RESET}")
                user_id = _ask("Your Telegram user ID", required=True)
            answers["telegram_user_id"] = user_id
    else:
        print(f"  {DIM}Skipped. You can add Telegram later in web settings.{RESET}")

    # ── Step 3: Web Access ───────────────────────────────────────

    _section("Step 3: Web Dashboard Credentials")
    print(f"""
{DIM}Set a username and password for the web dashboard.
You'll use this to log in at http://your-server:8080{RESET}
""")

    answers["web_username"] = _ask("Username", default="admin")
    while True:
        password = _ask("Password", required=True)
        if len(password) < 8:
            print(f"  {YELLOW}Password should be at least 8 characters.{RESET}")
            if not _ask_yn("Use it anyway?", default=False):
                continue
        answers["web_password"] = password
        break

    # Auto-generate session secret
    answers["session_secret"] = secrets.token_hex(32)

    # SSH password same as web by default
    answers["ssh_password"] = answers["web_password"]

    # ── Summary ──────────────────────────────────────────────────

    _section("Setup Summary")
    ai_name = next(
        p["name"] for p in AI_PROVIDERS.values()
        if p["provider"] == answers["ai_provider"]
    )
    print(f"""
  AI Provider:  {CYAN}{ai_name}{RESET}
  Telegram:     {GREEN + '✓ Configured' + RESET if answers.get('telegram_token') else DIM + '✗ Skipped' + RESET}
  Web Login:    {answers['web_username']} / {'*' * len(answers['web_password'])}
  SSH Password: {'*' * len(answers['ssh_password'])}
""")

    if answers.get("telegram_token"):
        print(f"  Bot Token:   {answers['telegram_token'][:8]}...{answers['telegram_token'][-4:]}")
        print(f"  User ID:     {answers['telegram_user_id']}")

    # ── Check for existing .env ──────────────────────────────────

    if env_file.exists():
        print(f"\n  {YELLOW}⚠  .env already exists.{RESET}")
        if not _ask_yn("Overwrite it?", default=False):
            # Save as .env.new instead
            env_file = project_root / ".env.new"
            print(f"  Saving to {env_file.name} instead.")

    # ── Write .env ───────────────────────────────────────────────

    env_content = _generate_env(answers)
    env_file.write_text(env_content)
    os.chmod(env_file, 0o600)
    print(f"\n  {GREEN}✓{RESET} Saved {env_file.name} ({env_file.stat().st_size} bytes, permissions 600)")

    # ── Docker ───────────────────────────────────────────────────

    _section("Step 4: Start Roost")

    # Check Docker is available
    docker_available = shutil.which("docker") is not None
    if not docker_available:
        print(f"""
  {RED}Docker not found on this system.{RESET}
  Install Docker first: https://docs.docker.com/engine/install/

  Once installed, run:
    cd {project_root}
    docker compose up -d
""")
        return

    # Check docker compose works
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode != 0:
            print(f"  {RED}docker compose not available. Install Docker Compose v2.{RESET}")
            return
    except (subprocess.TimeoutExpired, FileNotFoundError):
        print(f"  {RED}Could not run docker compose.{RESET}")
        return

    if _ask_yn("Build and start Roost now?"):
        print(f"\n  {DIM}Building container (this may take a few minutes)...{RESET}\n")

        # Build with feature flags
        build_cmd = _build_docker_compose_args(answers)
        build_result = subprocess.run(build_cmd, cwd=project_root)

        if build_result.returncode != 0:
            print(f"\n  {RED}Build failed. Check the output above for errors.{RESET}")
            return

        # Start
        print(f"\n  {DIM}Starting Roost...{RESET}\n")
        up_result = subprocess.run(
            ["docker", "compose", "up", "-d"],
            cwd=project_root
        )

        if up_result.returncode != 0:
            print(f"\n  {RED}Failed to start. Check: docker compose logs{RESET}")
            return

        print(f"""
{GREEN}{BOLD}╔══════════════════════════════════════════════╗
║            ✓  Roost is running!              ║
╚══════════════════════════════════════════════╝{RESET}

  Web dashboard:  http://your-server:8080
  Login:          {answers['web_username']} / (your password)
  SSH:            ssh dev@your-server -p 2222
""")
        if answers.get("telegram_token"):
            print(f"  Telegram:       Send /start to your bot")

        print(f"""
{DIM}Next steps:
  • Log into the web dashboard
  • Send /start to your Telegram bot
  • Add Google or Microsoft later in Settings{RESET}
""")
    else:
        print(f"""
  {DIM}When you're ready, run:
    cd {project_root}
    docker compose up -d{RESET}
""")


def main():
    """Entry point for roost-onboard."""
    run_onboard()


if __name__ == "__main__":
    main()
