#!/usr/bin/env python3
"""Generate docs/mcp-inventory.md from @mcp.tool()-decorated functions.

Walks roost/mcp/tools_*.py (core) and roost/extras/*/mcp/tools_*.py (bundles),
extracts every @mcp.tool()-decorated function name + first-line docstring,
writes a dated markdown file with totals + per-module tables.

Re-run any time tools are added/removed. The file is overwritten in place.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "mcp-inventory.md"


def is_mcp_tool_decorator(node: ast.AST) -> bool:
    if isinstance(node, ast.Call):
        node = node.func
    return (
        isinstance(node, ast.Attribute)
        and node.attr == "tool"
        and isinstance(node.value, ast.Name)
        and node.value.id == "mcp"
    )


def extract_tools(path: Path) -> list[tuple[str, str]]:
    tree = ast.parse(path.read_text())
    out: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not any(is_mcp_tool_decorator(d) for d in node.decorator_list):
            continue
        doc = ast.get_docstring(node) or ""
        first_line = doc.strip().split("\n", 1)[0].strip() or "—"
        out.append((node.name, first_line))
    return out


def render_module_section(rel: str, tools: list[tuple[str, str]]) -> str:
    lines = [f"### `{rel}` — {len(tools)} tools", ""]
    lines.append("| Tool | Description |")
    lines.append("|---|---|")
    for name, desc in sorted(tools):
        safe = desc.replace("|", "\\|")
        lines.append(f"| `{name}` | {safe} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    core_files = sorted((ROOT / "roost" / "mcp").glob("tools_*.py"))
    bundle_files = sorted((ROOT / "roost" / "extras").glob("*/mcp/tools_*.py"))

    core_results: list[tuple[str, list[tuple[str, str]]]] = []
    bundle_results: list[tuple[str, list[tuple[str, str]]]] = []
    core_count = 0
    bundle_count = 0

    for p in core_files:
        tools = extract_tools(p)
        if not tools:
            continue
        core_results.append((str(p.relative_to(ROOT)), tools))
        core_count += len(tools)

    for p in bundle_files:
        tools = extract_tools(p)
        if not tools:
            continue
        bundle_results.append((str(p.relative_to(ROOT)), tools))
        bundle_count += len(tools)

    total = core_count + bundle_count

    parts: list[str] = []
    parts.append("# MCP Tool Inventory")
    parts.append("")
    parts.append(
        f"**Total:** {total} tools across "
        f"{len(core_results) + len(bundle_results)} modules "
        f"({core_count} core + {bundle_count} bundle)"
    )
    parts.append("")
    parts.append(
        "Generated by `scripts/gen_mcp_inventory.py` from `@mcp.tool()` "
        "decorators. Do not edit by hand — re-run the script when tools "
        "are added or removed. Other docs (README, `platform-overview.md`, "
        "`mcp-server.md`, `CLAUDE.md`) link here as the single source of "
        "truth for the tool count."
    )
    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append(f"## Core ({core_count} tools, {len(core_results)} modules)")
    parts.append("")
    for rel, tools in core_results:
        parts.append(render_module_section(rel, tools))
    parts.append("---")
    parts.append("")
    parts.append(f"## Bundles ({bundle_count} tools, {len(bundle_results)} modules)")
    parts.append("")
    for rel, tools in bundle_results:
        parts.append(render_module_section(rel, tools))

    OUTPUT.write_text("\n".join(parts).rstrip() + "\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}: {total} tools ({core_count} core + {bundle_count} bundle)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
